- nodeset:
    name: emea-node
    nodes:
      - name: node1
        label: ubuntu-bionic
        
- nodeset:
    name: nafta-node
    nodes:
      - name: centosaws
        label: centos1
        
- nodeset:
    name: gate-node
    nodes:
      - name: gate
        label: centos76 

- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
    
- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
    
- job:
    name: gameoflifebuild
    run: playbooks/gameoflifebuild.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$


- project:
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node
    check_emea:
      jobs:
        - gameoflifebuild:
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKENgN8KDBktFnzReTWGs3w7T7LL3WTzCTHGo8HkAewVgszFFVejsBEsbmHq9qemJyYx"
            nodeset: emea-node
    check_nafta:
      jobs:
        - gameoflifebuild:
            host-vars: 
              node2:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKENgN8KDBktFnzReTWGs3w7T7LL3WTzCTHGo8HkAewVgszFFVejsBEsbmHq9qemJyYx"
            nodeset: nafta-node
    gate:
      jobs:
        - gameoflifebuild:
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSC8JkmgdCJ1SyqE3gtXEeyRYdQ2dTpE7oooHmgWW9WuKKBPrDtrfjzPfa9PMX7LSP"
            nodeset: nafta-node              
