- nodeset:
    name: emea_nafta_node
    nodes:
      - name: node1
        label: ubuntu-bionic
      - name: node2
        label: centos76
        
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76
        
- nodeset:
    name: emea-node
    nodes:
      - name: node1
        label: ubuntu-bionic        
        
- nodeset:
    name: gate-node
    nodes:
      - name: gate
        label: centos76 

- job:
    name: checklabelemea_datalocation
    run: playbooks/buildlocation_emea.yaml
    parent: base
    
    
- job:
    name: checklabelnafta_datalocation
    run: playbooks/buildlocation_nafta.yaml
    parent: base
    
      
- job:
    name: checklabel_both
    run: playbooks/buildlocation_both.yaml
    parent: base
    
- job:
    name: buildvariables
    run: playbooks/allvars.yml
    parent: base    
       
    
- job:
    name: buildcode
    run: playbooks/buildcode.yaml
    parent: buildvariables
    
    
      
- job:
    name: buildimage
    run: playbooks/buildimage.yaml
    parent: buildcode       
      
- job:
    name: builddeploy
    run: playbooks/builddeploy.yaml
    parent: buildimage
    
- project:
    checklabel_both:
      jobs:
       - checklabel_both:
           nodeset: emea-node
    checklabel_nafta_datalocation:
      jobs:
       - checklabelnafta_datalocation:
           nodeset: nafta-node      
    checklabel_emea_datalocation:
      jobs:
       - checklabelemea_datalocation:
           nodeset: nafta-node          
    check_emea:
      jobs:
        - buildvariables:
            nodeset: emea-node
        - buildcode:
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            dependencies:
              - buildvariables
            nodeset: emea-node            
        - buildimage:
            dependencies:
              - buildcode
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea-node            
        - builddeploy:
            dependencies:
              - buildcode
              - buildimage
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea-node
    check_nafta:
      jobs:
        - buildvariables:
            nodeset: nafta-node
        - buildcode:
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "52.66.201.12:9083"
            dependencies:
              - buildvariables 
            nodeset: nafta-node
        - buildimage:
            dependencies:
              - buildcode
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "52.66.201.12:9083"
            nodeset: nafta-node
        - builddeploy:
            dependencies:
              - buildcode
              - buildimage
            host-vars:
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "52.66.201.12:9083"
            nodeset: nafta-node
