- nodeset:
    name: emea_nafta_node
    nodes:
      - name: node1
        label: ubuntu-bionic
      - name: node2
        label: centos76
        
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76
        
- nodeset:
    name: emea-node
    nodes:
      - name: node1
        label: ubuntu-bionic        
        
- nodeset:
    name: gate-node
    nodes:
      - name: gate
        label: centos76 

- job:
    name: checklabelemea_datalocation
    run: playbooks/buildlocation_emea.yaml
    parent: base
    
    
- job:
    name: checklabelnafta_datalocation
    run: playbooks/buildlocation_nafta.yaml
    parent: base
    
      
- job:
    name: checklabel_both
    run: playbooks/buildlocation_both.yaml
    parent: base
    
- job:
    name: build_variables
    run: playbooks/allvars.yml
    parent: base    
       
    
- job:
    name: build_code
    run: playbooks/buildcode.yaml
    parent: build_variables
    
    
      
- job:
    name: build_push_image
    run: playbooks/buildimage.yaml
    parent: build_variables       
      
- job:
    name: deploy_kubernetes
    run: playbooks/builddeploy.yaml
    parent: build_variables
    
- project:
    checklabel_both:
      jobs:
       - checklabel_both:
           nodeset: emea-node
    checklabel_nafta_datalocation:
      jobs:
       - checklabelnafta_datalocation:
           nodeset: nafta-node      
    checklabel_emea_datalocation:
      jobs:
       - checklabelemea_datalocation:
           nodeset: nafta-node          
    check_emea:
      jobs:
        - build_variables:
            nodeset: emea-node
        - build_code:
            dependencies:
              - build_variables
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea-node            
        - build_push_image:
            dependencies:
              - build_variables 
              - build_code
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea-node            
        - deploy_kubernetes:
            dependencies:
              - build_variables
              - build_code
              - build_push_image
            host-vars:
              node1:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea-node
    check_nafta:
      jobs:
        - build_variables:
            nodeset: nafta-node
        - build_code:
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "13.232.239.157:9083" 
            nodeset: nafta-node
        - build_push_image:
            dependencies:
              - build_code
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "13.232.239.157:9083"
            nodeset: nafta-node
        - deploy_kubernetes:
            dependencies:
              - build_code
              - build_push_image
            host-vars:
              node2:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
                jfrog_docker: "13.232.239.157:9083"
            nodeset: nafta-node
