- hosts: all
  tasks:
    - name: pull request dependent job
      debug:
        msg: "In Check label emea and nafta job"
    - name: getting the pull id of pull request
      debug:
       msg: "{{ zuul.change_url }}"
    - shell: |
         echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
    - name: getting the project name of pull request
      debug:
       msg: "{{ zuul.project.name }}"
    - name: display pull id
      debug:
       msg: "{{ pullid }}"
    - set_fact:
       pull_id="{{pullid.stdout}}"
    - shell: |
           curl -s https://api.github.com/repos/{{ zuul.project.name }}/pulls/{{ pull_id }}| jq .head.ref
      register: branch
      args:
        warn: false
    - set_fact:
       branch_name="{{branch.stdout}}"
    - debug:
       msg: "{{ branch_name }}"

    - shell: |
           curl -s curl https://github.com/{{ zuul.project.name }}/blob/{{ branch_name }}/build_location| grep 'js-file-line">'   | sed s/\<.*le-line\"\>//g | sed s/\<.*td\>//g | sed 's/ //g'|grep -i ROSbagDatalocation | cut -d "=" -f 2 
      register: name
      failed_when: '"both" not in name.stdout'
    - set_fact:
       location="{{name.stdout}}"
       
    - shell: |
           curl -s curl https://github.com/{{ zuul.project.name }}/blob/{{ branch_name }}/build_location| grep 'js-file-line">'   | sed s/\<.*le-line\"\>//g | sed s/\<.*td\>//g | sed 's/ //g'|grep -i InputScenario1Data | cut -d "=" -f 2 
      register: inputdata_location_1
      
    - set_fact:
       input_location_1={{inputdata_location.stdout}}
       
    - shell: |
           curl -s curl https://github.com/{{ zuul.project.name }}/blob/{{ branch_name }}/build_location| grep 'js-file-line">'   | sed s/\<.*le-line\"\>//g | sed s/\<.*td\>//g | sed 's/ //g'|grep -i InputScenario2Data | cut -d "=" -f 2 
      register: inputdata_location_2
      
    - set_fact:
       input_location_2={{inputdata_location.stdout}}    
       
    - shell: |
           curl -s curl https://github.com/{{ zuul.project.name }}/blob/{{ branch_name }}/build_location| grep 'js-file-line">'   | sed s/\<.*le-line\"\>//g | sed s/\<.*td\>//g | sed 's/ //g'|grep -i Emea_artifactlocation | cut -d "=" -f 2 
      register: emea_artifact_location
      
    - set_fact:
       emea_artifacts={{emea_artifact_location.stdout}}   
       
    - shell: |
           curl -s curl https://github.com/{{ zuul.project.name }}/blob/{{ branch_name }}/build_location| grep 'js-file-line">'   | sed s/\<.*le-line\"\>//g | sed s/\<.*td\>//g | sed 's/ //g'|grep -i Nafta_artifactlocation | cut -d "=" -f 2 
      register: nafta_artifact_location
      
    - set_fact:
       nafta_artifacts={{nafta_artifact_location.stdout}}    
       
   
