- hosts: all
  tasks:
#    - shell: |
#           echo {{ zuul.change_url }} | cut -d '/' -f 7
#      register: pullid
      
    - name: Pull the jar file 
      get_url:
        url: "{{ jfrog }}/artifactory/generic-local/gameoflife-{{ zuul_pull_id }}.war"
        dest: /home/ec2-user/work
        
    - set_fact: set input_location variable for emea
        input_location_emea={{zuul_input_location_1.stdout}}
        
    - set_fact: set input_location variable for emea
        input_location_nafta={{zuul_input_location_2.stdout}}    
        
    - name: Get the pipeline name in which job is being run
      debug:
        msg : "{{ zuul.pipeline }}"     
        
    - shell: |
           echo {{ zuul.pipeline }} | cut -d '_' -f 2
      register: location
        
    - set_fact:
       data_location="{{location.stdout}}"

     - shell: |
            if [{{ data_location }} == "emea"]
             inputfiles_location="{{ zuul_input_location_1 }}"
            else
             inputfiles_location="{{ zuul_input_location_2.stdout }}"" 
       
#    - name: Copy the input files from project work dir to home folder of user
#      shell: |
#           cp -ar ~/work/{{ data_location }}_input /home/ec2-user/work/
##      register: copy_status     
                    
    - name: build the docker file
      shell: | 
           echo "FROM {{ jfrog_docker }}/docker-local/tomcat:latest" > /home/ec2-user/work/Dockerfile
           echo "COPY gameoflife-{{ pullid.stdout }}.war   /usr/local/tomcat/webapps/" >> /home/ec2-user/work/Dockerfile
           echo "COPY $inputfiles_location_input   /usr/local/webapps/" >> /home/ec2-user/work/Dockerfile
           echo "RUN ls -laR /usr/local/webapps/*" >> /home/ec2-user/work/Dockerfile
    - name : build the docker image 
      shell: |
           cd /home/ec2-user/work
           docker build -t {{ jfrog_docker }}/docker-local/tomcat:{{ pullid.stdout }} . 
           
    - name: login to docker to push the images
      shell: |
           docker login -u admin -p password  {{ jfrog_docker }}
      register: login_status
           
    - name : push the docker images 
      shell: |
           docker push {{ jfrog_docker }}/docker-local/tomcat:{{ pullid.stdout }} 
      when: login_status is succeeded         
      
#    - name: deploy to kubernetes
#      shell: |
#             cd ~/gameoflife
#             kubectl apply -f kubedeploy.yml
