- hosts: all
  tasks:
#    - shell: |
#           echo {{ zuul.change_url }} | cut -d '/' -f 7
#      register: pullid
      
    - name: Pull the jar file 
      get_url:
        url: "{{ jfrog }}/artifactory/generic-local/gameoflife-{{ pullid.stdout }}.war"
        dest: /home/ec2-user/work
        
    - name: Get the pipeline name in which job is being run
      debug:
        msg : "{{ zuul.pipeline }}"     
        
    - shell: |
           echo {{ zuul.pipeline }} | cut -d '_' -f 2
      register: location
        
    - set_fact:
       data_location="{{location.stdout}}"
                    
    - name: build the docker file
      shell: | 
           echo "FROM ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083/docker-local/tomcat:v1.2" > /home/ec2-user/work/Dockerfile
           echo "COPY gameoflife-{{ pullid.stdout }}.war   /usr/local/tomcat/webapps/" >> /home/ec2-user/work/Dockerfile
           echo "COPY /home/ec2-user/work/{{ zuul.project.short_name }}/{{ data_location }}_input/*.*   /usr/local/webapps" >> /home/ec2-user/work/Dockerfile
            
    - name : build the docker image 
      shell: |
           cd /home/ec2-user/work
           docker build -t {{ jfrog_docker }}/docker-local/tomcat:{{ pullid.stdout }} . 
           
    - name: login to docker to push the images
      shell: |
           docker login -u admin -p password  {{ jfrog_docker }}
      register: login_status
           
    - name : push the docker images 
      shell: |
           docker push {{ jfrog_docker }}/docker-local/tomcat:{{ pullid.stdout }} 
      when: login_status is succeeded         
      
#    - name: deploy to kubernetes
#      shell: |
#             cd ~/gameoflife
#             kubectl apply -f kubedeploy.yml
